apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: homework
type: Opaque
data:
  # Пароль в base64: echo -n 'yourpassword' | base64
  # Пример: echo -n 'SuperSecret123' | base64
  DB_PASSWORD: Q2hhbmdlTWVQbGVhc2U=
